steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=NEXT_PUBLIC_RESEARCH_LANDING=true'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aprilio-site'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aprilio-site']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aprilio-site'
      - '--image=gcr.io/$PROJECT_ID/aprilio-site'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=8080'
images:
  - 'gcr.io/$PROJECT_ID/aprilio-site'
timeout: '1200s'
